export const COUNTRY_FLAGS: Record<string, string> = {
  "Algeria": "🇩🇿",
  "Angola": "🇦🇴",
  "Benin": "🇧🇯",
  "Botswana": "🇧🇼",
  "Burkina Faso": "🇧🇫",
  "Burundi": "🇧🇮",
  "Cameroon": "🇨🇲",
  "Cape Verde": "🇨🇻",
  "Central African Republic": "🇨🇫",
  "Chad": "🇹🇩",
  "Comoros": "🇰🇲",
  "DR Congo": "🇨🇩",
  "Djibouti": "🇩🇯",
  "Egypt": "🇪🇬",
  "Equatorial Guinea": "🇬🇶",
  "Eritrea": "🇪🇷",
  "Eswatini": "🇸🇿",
  "Ethiopia": "🇪🇹",
  "Gabon": "🇬🇦",
  "Gambia": "🇬🇲",
  "Ghana": "🇬🇭",
  "Guinea": "🇬🇳",
  "Guinea-Bissau": "🇬🇼",
  "Ivory Coast": "🇨🇮",
  "Kenya": "🇰🇪",
  "Lesotho": "🇱🇸",
  "Liberia": "🇱🇷",
  "Libya": "🇱🇾",
  "Madagascar": "🇲🇬",
  "Malawi": "🇲🇼",
  "Mali": "🇲🇱",
  "Mauritania": "🇲🇷",
  "Mauritius": "🇲🇺",
  "Morocco": "🇲🇦",
  "Mozambique": "🇲🇿",
  "Namibia": "🇳🇦",
  "Niger": "🇳🇪",
  "Nigeria": "🇳🇬",
  "Rwanda": "🇷🇼",
  "Senegal": "🇸🇳",
  "Sierra Leone": "🇸🇱",
  "Somalia": "🇸🇴",
  "South Africa": "🇿🇦",
  "South Sudan": "🇸🇸",
  "Sudan": "🇸🇩",
  "Tanzania": "🇹🇿",
  "Togo": "🇹🇬",
  "Tunisia": "🇹🇳",
  "Uganda": "🇺🇬",
  "Zambia": "🇿🇲",
  "Zimbabwe": "🇿🇼",
};

export type Region = "All" | "West Africa" | "East Africa" | "North Africa" | "Southern Africa" | "Central Africa";

export const COUNTRY_REGIONS: Record<string, Region> = {
  "Algeria": "North Africa",
  "Angola": "Southern Africa",
  "Benin": "West Africa",
  "Botswana": "Southern Africa",
  "Burkina Faso": "West Africa",
  "Burundi": "East Africa",
  "Cameroon": "Central Africa",
  "Cape Verde": "West Africa",
  "Central African Republic": "Central Africa",
  "Chad": "Central Africa",
  "Comoros": "East Africa",
  "DR Congo": "Central Africa",
  "Djibouti": "East Africa",
  "Egypt": "North Africa",
  "Equatorial Guinea": "Central Africa",
  "Eritrea": "East Africa",
  "Eswatini": "Southern Africa",
  "Ethiopia": "East Africa",
  "Gabon": "Central Africa",
  "Gambia": "West Africa",
  "Ghana": "West Africa",
  "Guinea": "West Africa",
  "Guinea-Bissau": "West Africa",
  "Ivory Coast": "West Africa",
  "Kenya": "East Africa",
  "Lesotho": "Southern Africa",
  "Liberia": "West Africa",
  "Libya": "North Africa",
  "Madagascar": "Southern Africa",
  "Malawi": "Southern Africa",
  "Mali": "West Africa",
  "Mauritania": "North Africa",
  "Mauritius": "Southern Africa",
  "Morocco": "North Africa",
  "Mozambique": "Southern Africa",
  "Namibia": "Southern Africa",
  "Niger": "West Africa",
  "Nigeria": "West Africa",
  "Rwanda": "East Africa",
  "Senegal": "West Africa",
  "Sierra Leone": "West Africa",
  "Somalia": "East Africa",
  "South Africa": "Southern Africa",
  "South Sudan": "East Africa",
  "Sudan": "North Africa",
  "Tanzania": "East Africa",
  "Togo": "West Africa",
  "Tunisia": "North Africa",
  "Uganda": "East Africa",
  "Zambia": "Southern Africa",
  "Zimbabwe": "Southern Africa",
};

export const REGIONS: Region[] = [
  "All",
  "West Africa",
  "East Africa",
  "North Africa",
  "Southern Africa",
  "Central Africa",
];

export const REGION_COLORS: Record<Region, string> = {
  "All": "bg-primary text-primary-foreground",
  "West Africa": "bg-amber-600 text-white",
  "East Africa": "bg-emerald-600 text-white",
  "North Africa": "bg-sky-600 text-white",
  "Southern Africa": "bg-purple-600 text-white",
  "Central Africa": "bg-rose-600 text-white",
};

export const REGION_BADGE_COLORS: Record<Region, string> = {
  "All": "bg-primary/10 text-primary",
  "West Africa": "bg-amber-100 text-amber-700",
  "East Africa": "bg-emerald-100 text-emerald-700",
  "North Africa": "bg-sky-100 text-sky-700",
  "Southern Africa": "bg-purple-100 text-purple-700",
  "Central Africa": "bg-rose-100 text-rose-700",
};
