export const COUNTRY_FLAGS: Record<string, string> = {
  "Algeria": "🇩🇿",
  "Angola": "🇦🇴",
  "Benin": "🇧🇯",
  "Botswana": "🇧🇼",
  "Burkina Faso": "🇧🇫",
  "Burundi": "🇧🇮",
  "Cameroon": "🇨🇲",
  "Cape Verde": "🇨🇻",
  "Central African Republic": "🇨🇫",
  "Chad": "🇹🇩",
  "Comoros": "🇰🇲",
  "DR Congo": "🇨🇩",
  "Djibouti": "🇩🇯",
  "Egypt": "🇪🇬",
  "Equatorial Guinea": "🇬🇶",
  "Eritrea": "🇪🇷",
  "Eswatini": "🇸🇿",
  "Ethiopia": "🇪🇹",
  "Gabon": "🇬🇦",
  "Gambia": "🇬🇲",
  "Ghana": "🇬🇭",
  "Guinea": "🇬🇳",
  "Guinea-Bissau": "🇬🇼",
  "Ivory Coast": "🇨🇮",
  "Kenya": "🇰🇪",
  "Lesotho": "🇱🇸",
  "Liberia": "🇱🇷",
  "Libya": "🇱🇾",
  "Madagascar": "🇲🇬",
  "Malawi": "🇲🇼",
  "Mali": "🇲🇱",
  "Mauritania": "🇲🇷",
  "Mauritius": "🇲🇺",
  "Morocco": "🇲🇦",
  "Mozambique": "🇲🇿",
  "Namibia": "🇳🇦",
  "Niger": "🇳🇪",
  "Nigeria": "🇳🇬",
  "Rwanda": "🇷🇼",
  "Senegal": "🇸🇳",
  "Sierra Leone": "🇸🇱",
  "Somalia": "🇸🇴",
  "South Africa": "🇿🇦",
  "South Sudan": "🇸🇸",
  "Sudan": "🇸🇩",
  "Tanzania": "🇹🇿",
  "Togo": "🇹🇬",
  "Tunisia": "🇹🇳",
  "Uganda": "🇺🇬",
  "Zambia": "🇿🇲",
  "Zimbabwe": "🇿🇼",
};

// ISO 3166-1 alpha-2 codes, lowercase — used to build real flag image URLs
// instead of relying on emoji flag glyphs. Windows (and some Linux distros)
// have no font glyph for regional-indicator flag emoji and fall back to
// showing the raw two-letter code as plain text (e.g. "ZA" instead of 🇿🇦).
// Real flag images render identically across every OS.
export const COUNTRY_CODES: Record<string, string> = {
  "Algeria": "dz",
  "Angola": "ao",
  "Benin": "bj",
  "Botswana": "bw",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Cameroon": "cm",
  "Cape Verde": "cv",
  "Central African Republic": "cf",
  "Chad": "td",
  "Comoros": "km",
  "DR Congo": "cd",
  "Djibouti": "dj",
  "Egypt": "eg",
  "Equatorial Guinea": "gq",
  "Eritrea": "er",
  "Eswatini": "sz",
  "Ethiopia": "et",
  "Gabon": "ga",
  "Gambia": "gm",
  "Ghana": "gh",
  "Guinea": "gn",
  "Guinea-Bissau": "gw",
  "Ivory Coast": "ci",
  "Kenya": "ke",
  "Lesotho": "ls",
  "Liberia": "lr",
  "Libya": "ly",
  "Madagascar": "mg",
  "Malawi": "mw",
  "Mali": "ml",
  "Mauritania": "mr",
  "Mauritius": "mu",
  "Morocco": "ma",
  "Mozambique": "mz",
  "Namibia": "na",
  "Niger": "ne",
  "Nigeria": "ng",
  "Rwanda": "rw",
  "Senegal": "sn",
  "Sierra Leone": "sl",
  "Somalia": "so",
  "South Africa": "za",
  "South Sudan": "ss",
  "Sudan": "sd",
  "Tanzania": "tz",
  "Togo": "tg",
  "Tunisia": "tn",
  "Uganda": "ug",
  "Zambia": "zm",
  "Zimbabwe": "zw",
};

export type Region = "All" | "West Africa" | "East Africa" | "North Africa" | "Southern Africa" | "Central Africa";

export const COUNTRY_REGIONS: Record<string, Region> = {
  "Algeria": "North Africa",
  "Angola": "Southern Africa",
  "Benin": "West Africa",
  "Botswana": "Southern Africa",
  "Burkina Faso": "West Africa",
  "Burundi": "East Africa",
  "Cameroon": "Central Africa",
  "Cape Verde": "West Africa",
  "Central African Republic": "Central Africa",
  "Chad": "Central Africa",
  "Comoros": "East Africa",
  "DR Congo": "Central Africa",
  "Djibouti": "East Africa",
  "Egypt": "North Africa",
  "Equatorial Guinea": "Central Africa",
  "Eritrea": "East Africa",
  "Eswatini": "Southern Africa",
  "Ethiopia": "East Africa",
  "Gabon": "Central Africa",
  "Gambia": "West Africa",
  "Ghana": "West Africa",
  "Guinea": "West Africa",
  "Guinea-Bissau": "West Africa",
  "Ivory Coast": "West Africa",
  "Kenya": "East Africa",
  "Lesotho": "Southern Africa",
  "Liberia": "West Africa",
  "Libya": "North Africa",
  "Madagascar": "Southern Africa",
  "Malawi": "Southern Africa",
  "Mali": "West Africa",
  "Mauritania": "North Africa",
  "Mauritius": "Southern Africa",
  "Morocco": "North Africa",
  "Mozambique": "Southern Africa",
  "Namibia": "Southern Africa",
  "Niger": "West Africa",
  "Nigeria": "West Africa",
  "Rwanda": "East Africa",
  "Senegal": "West Africa",
  "Sierra Leone": "West Africa",
  "Somalia": "East Africa",
  "South Africa": "Southern Africa",
  "South Sudan": "East Africa",
  "Sudan": "North Africa",
  "Tanzania": "East Africa",
  "Togo": "West Africa",
  "Tunisia": "North Africa",
  "Uganda": "East Africa",
  "Zambia": "Southern Africa",
  "Zimbabwe": "Southern Africa",
};

export const REGIONS: Region[] = [
  "All",
  "West Africa",
  "East Africa",
  "North Africa",
  "Southern Africa",
  "Central Africa",
];

// Solid backgrounds for the active/selected region pill. Uses the
// --region-* CSS tokens already defined in index.css (and already used by
// Sidebar.tsx's "Browse by Region" widget) instead of hardcoded Tailwind
// palette colors, so this page's region colors actually match the rest of
// the site rather than being a disconnected purple/amber/emerald set.
// Text on these fills is --paper, not white: under the dark theme both
// --accent and the --region-* tokens are light, so white-on-light failed
// contrast badly (the active "All" pill measured 2.16:1). Dark-on-light is
// the correct pairing now.
export const REGION_COLORS: Record<Region, string> = {
  "All": "bg-[var(--accent)] text-[var(--paper)]",
  "West Africa": "bg-[var(--region-west)] text-[var(--paper)]",
  "East Africa": "bg-[var(--region-east)] text-[var(--paper)]",
  "North Africa": "bg-[var(--region-north)] text-[var(--paper)]",
  "Southern Africa": "bg-[var(--region-south)] text-[var(--paper)]",
  "Central Africa": "bg-[var(--region-central)] text-[var(--paper)]",
};

// Tinted badge version (15% opacity fill + full-strength text) for the
// smaller count badges and the "filtered by region" label.
export const REGION_BADGE_COLORS: Record<Region, string> = {
  "All": "bg-[var(--accent)]/15 text-[var(--accent)]",
  "West Africa": "bg-[var(--region-west)]/15 text-[var(--region-west)]",
  "East Africa": "bg-[var(--region-east)]/15 text-[var(--region-east)]",
  "North Africa": "bg-[var(--region-north)]/15 text-[var(--region-north)]",
  "Southern Africa": "bg-[var(--region-south)]/20 text-[var(--region-south)]",
  "Central Africa": "bg-[var(--region-central)]/15 text-[var(--region-central)]",
};
