-- Row Level Security policies for Supabase.
-- Not generated by drizzle-kit (RLS isn't part of the Drizzle schema model) —
-- apply manually via the Supabase SQL editor or `psql -f`, after 0000.
--
-- The API server and the GitHub Actions ingestion job connect with the
-- service_role / postgres connection string, which bypasses RLS entirely, so
-- these policies are defense-in-depth for the anon/authenticated roles only
-- (relevant if anything is ever queried directly from the browser).

ALTER TABLE "sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "articles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscribers" ENABLE ROW LEVEL SECURITY;

-- Public read-only feed data.
CREATE POLICY "public_read" ON "sources" FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public_read" ON "articles" FOR SELECT TO anon, authenticated USING (true);

-- subscribers: no anon/authenticated policies at all — default-deny. Email
-- addresses are only ever read/written through the API server.
